### ISSUE TITLE
Top cut off through score

### ISSUE THREAD

**Issue by amoore2600** [MiSTer-devel/Arcade-1943_MiSTer#2]
The top of 1943 is cut off and it cuts in the scores. See picture compared MAME. 

![IMG_20190528_183549](https://user-images.githubusercontent.com/3682337/60366909-e0715000-99ba-11e9-8134-a69bf6e04aed.jpg)

 
Video from  mame https://youtu.be/S1OFvhEIOIc

**Comment by taw6** [comment]
I have this same problem

**Comment by jotego** [comment]
Get the latest version from the official repo of this core.

**Comment by amoore2600** [comment]
I can confirm the latest version from the official JT repo fixes this issue. Will this ever be updated in the MiSTer github?

**Comment by jotego** [comment]
Thank you for reporting it. I will verify and fix it.
Eventually the cores will be ported to the MiSTer repository for archiving (although I will not do that job myself). At the moment I prefer if they are not moved as I still change many common files, create new common files and it suits me better for development to keep a different folder structure. 
It's better if you post issues [here ](https://github.com/jotego/jt_gng)for the time being.
