### ISSUE TITLE
core no longer works after update

### ISSUE THREAD

**Issue by damanloox** [MiSTer-devel/Arcade-1943_MiSTer#6]
the core no longer works after latest update.. neither Europe nor US rom works anymore...

**Comment by pdevine** [comment]
What does it look like for you?  When I tried loading it up (with the correct ROM), it just displays garbage. I'm using a 256MB RAM board and was wondering if that was part of the reason.

**Comment by jotego** [comment]
Yes, the 256MB module is probably the reason. I don’t have that module.
Didn’t even know it existed. The core supports 32 and 128Mb modules.

**Comment by sorgelig** [comment]
There is no 256MB module. Just a victim of false ads :)

**Comment by pdevine** [comment]
My fingers apparently had a mind of their own when I typed that. Yes, it's 128MB. :-D

It still doesn't load correctly though, although the ROM does pass the checksums.

**Comment by pdevine** [comment]
I don't know how similar the 1943 board is to the 1942 board, however 1942 works correctly.

**Comment by pdevine** [comment]
@jotego did this get fixed?

**Comment by jotego** [comment]
Yes, please refer to my repository for CAPCOM games.
